### ISSUE TITLE
Auth URL unreadable in logs

### ISSUE THREAD

**Issue by choephix** [ServerContainers/google-drive-ocamlfuse#1]
Thanks for the amazing effort in helping others who need a quick and easily reversible way to mount gdrive.

However, when I run the container image, it ask me to go to a URL to authorize, except I don't see the URL in the log 😅

Please advise

![image](https://user-images.githubusercontent.com/962412/209524573-5676c551-f26d-4ddb-aabf-8b9637f66740.png)

This has been tried with `docker-compose`, inside Portainer, and via regular `ssh` + `docker run`, all on Raspberry Pi 4B

![image](https://user-images.githubusercontent.com/962412/209524782-19b0a530-e504-4d13-a9f6-db202a2a05c3.png)

**Comment by MarvAmBass** [comment]
thanks I'll take a look

**Comment by MarvAmBass** [comment]
I've fixed everything, new version is already available - but I'll repush a new build within the next hour

have fun using this container :)
